"""add new order

Revision ID: 284ed7bf8f5a
Revises: 9d66be019aaf
Create Date: 2025-08-30 01:58:50.999220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284ed7bf8f5a'
down_revision = '9d66be019aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
