"""modify Quizz

Revision ID: 4c32b53b2221
Revises: 809e30f7b688
Create Date: 2025-09-05 14:44:14.108231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c32b53b2221'
down_revision = '809e30f7b688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('blooms_level', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('blooms_level')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
