"""new models update

Revision ID: 809e30f7b688
Revises: 7bd5db707aaf
Create Date: 2025-09-05 00:53:13.280103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '809e30f7b688'
down_revision = '7bd5db707aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
